# -*- coding: utf-8 -*-
{
    'name': 'AssetFlow Base',
    'version': '18.0.1.0.0',
    'category': 'Asset Management',
    'summary': 'Core module for AssetFlow - Enterprise Asset & Resource Management',
    'description': "Core foundation for Department, Employee, Category and Security Management",
    'author': 'AssetFlow Team',
    'website': 'https://assetflow.example.com',
    'license': 'LGPL-3',
    'depends': ['base', 'mail'],
    'data': [
        'security/groups.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/department_sequence.xml',
        'data/role_data.xml',
        'data/category_data.xml',
        'views/actions.xml',
        'views/menus.xml',
        'views/department_views.xml',
        'views/employee_views.xml',
        'views/asset_category_views.xml',
        'views/role_views.xml',
        'wizard/promote_employee_views.xml',
    ],
    'demo': ['demo/demo.xml'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
